# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accueil', '0002_creation_comptes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'appréciations',
                'verbose_name': 'appréciation',
            },
        ),
        migrations.CreateModel(
            name='AppreciationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('colles', models.ManyToManyField(to='accueil.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pied_bulletin', models.TextField(verbose_name='Appréciation du conseil de classe')),
                ('appreciations', models.ManyToManyField(through='devoirs.Appreciation', to='accueil.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='ConcoursBlanc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('date', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Classe')),
            ],
            options={
                'verbose_name_plural': 'concours blancs',
                'verbose_name': 'concours blanc',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConcoursBlancMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('option', models.BooleanField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('concours_blanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.ConcoursBlanc')),
            ],
            options={
                'abstract': False,
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ConcoursTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='ConcoursTemplateMatiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('option', models.BooleanField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.ConcoursTemplate')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Matiere')),
            ],
            options={
                'abstract': False,
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('limite_saisie', models.DateField()),
                ('description', models.TextField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Classe')),
            ],
            options={
                'verbose_name_plural': 'conseils de classe',
                'verbose_name': 'conseil de classe',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom du devoir')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Matiere')),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Prof')),
            ],
            options={
                'verbose_name_plural': 'devoirs',
                'verbose_name': 'devoir',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DevoirNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.PositiveSmallIntegerField(choices=[(1, 'Noté'), (2, 'Absent'), (3, 'Absent excusé'), (4, 'Non noté')])),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('devoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.Devoir')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Eleve')),
            ],
            options={
                'verbose_name_plural': 'notes obtenues',
                'verbose_name': 'note obtenue',
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'périodes',
                'verbose_name': 'période',
                'ordering': ['-fin', '-debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeDevoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('coefficient', models.SmallIntegerField(verbose_name='Coefficient par défaut')),
            ],
            options={
                'verbose_name_plural': 'types de devoir',
                'verbose_name': 'type de devoir',
            },
        ),
        migrations.AddField(
            model_name='devoir',
            name='type_devoir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devoirs.TypeDevoir'),
        ),
        migrations.AddField(
            model_name='conseil',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='devoirs.Periode'),
        ),
        migrations.AddField(
            model_name='conseil',
            name='president',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concourstemplate',
            name='matieres',
            field=models.ManyToManyField(through='devoirs.ConcoursTemplateMatiere', to='accueil.Matiere'),
        ),
        migrations.AddField(
            model_name='concoursblancmatiere',
            name='devoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.Devoir'),
        ),
        migrations.AddField(
            model_name='concoursblancmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Matiere'),
        ),
        migrations.AddField(
            model_name='concoursblanc',
            name='matieres',
            field=models.ManyToManyField(through='devoirs.ConcoursBlancMatiere', to='accueil.Matiere'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='conseil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.Conseil'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Eleve'),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='conseil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.Conseil'),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Matiere'),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='notes',
            field=models.ManyToManyField(to='devoirs.DevoirNote'),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Prof'),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='debut',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='fin',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='appreciationtemplate',
            name='moyenne_auto',
            field=models.BooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='appreciationtemplate',
            unique_together=set([('conseil', 'professeur', 'matiere')]),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoirs.Bulletin'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='colles',
            field=models.ManyToManyField(to='accueil.Note'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Matiere'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='notes',
            field=models.ManyToManyField(to='devoirs.DevoirNote'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='professeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.Prof'),
        ),
        migrations.AddField(
            model_name='appreciation',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devoirs.AppreciationTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='conseil',
            unique_together=set([('periode', 'classe')]),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together=set([('conseil', 'eleve')]),
        ),
        migrations.AlterUniqueTogether(
            name='appreciation',
            unique_together=set([('bulletin', 'matiere')]),
        ),
        migrations.AlterUniqueTogether(
            name='periode',
            unique_together=set([('debut', 'fin')]),
        ),
    ]
